### ISSUE TITLE
Update postmark.js to v2.2.5 to benefit of the /docs 30 Mo removed

### ISSUE THREAD

**Issue by j1348** [killmenot/nodemailer-postmark-transport#14]
This is related to this issue https://github.com/wildbit/postmark.js/issues/48

**Comment by killmenot** [comment]
It's not needed.
https://github.com/killmenot/nodemailer-postmark-transport/blob/6d6a2a7715accec5c6e8266ebcd552996be157ff/package.json#L49
Once you install `nodemailer-postmark-transport` it loads latest postmark version bases on semver.
`^2.2.3` means `>= 2.0.0 < 3.0.0`
<img width="570" alt="Screenshot 2019-05-13 17 28 06" src="https://user-images.githubusercontent.com/119337/57629455-7d5f6180-75a4-11e9-81e9-7c3e3f72b742.png">
