### ISSUE TITLE
Issues sometimes sending emails on vercel (serverless)

### ISSUE THREAD

**Issue by Powersource** [killmenot/nodemailer-postmark-transport#20]
We basically ran into what we think is this issue in production https://stackoverflow.com/questions/65631481/nodemailer-in-vercel-not-sending-email-in-production However we do already use async/await, so I suspect that it was our usage of this library that's the issue.

**Comment by Powersource** [comment]
Wait no, might have been a missing await on our end anyway

**Comment by killmenot** [comment]
@Powersource could you point where? TBH, I'm not follow the issue description
