### ISSUE TITLE
Add support for templates?

### ISSUE THREAD

**Issue by SabeehY** [killmenot/nodemailer-postmark-transport#4]
Templates are really a very strong to use Postmark for me, any way we can incorporate that into this?

**Comment by killmenot** [comment]
@SabeehY Please post a link to templates docs here

**Comment by SabeehY** [comment]
http://developer.postmarkapp.com/developer-api-templates.html

**Comment by vhpoet** [comment]
any news on this?

**Comment by killmenot** [comment]
Added templates support via https://github.com/killmenot/nodemailer-postmark-transport/commit/9e33d4c21aa9c0acddcc901fdfa74e1d86082e35. Will release a new version in a couple of days

**Comment by killmenot** [comment]
Published
