### ISSUE TITLE
replyTo field not working

### ISSUE THREAD

**Issue by drschwabe** [killmenot/nodemailer-postmark-transport#6]
Is replyTo supported with Postmark ?  I have a basic message: 
```
  var msg = {
    to: 'john@gmail.com',  
    replyTo : 'sally@gmail.com',     
    subject:`Submission received`, 
    from : '"ABC Company" <signups@abccompany.com>', 
    html: `<p>Thank-you for your recent submission....</p>`
```

The message delivers fine with all above properties except there is no replyTo; when I hit reply the message recipient is signups@abccompany.com in this example it should be sally@gmail.com

**Comment by killmenot** [comment]
@drschwabe Hi, `replyTo` is supported by Postmark but was missed in this lib. I added it via https://github.com/killmenot/nodemailer-postmark-transport/commit/07785acdb969b25fd4ea6cf5fda686f4bc7dff69. Will bump a new version in a couple of days or sooner

**Comment by drschwabe** [comment]
Great!

**Comment by killmenot** [comment]
Published
