### ISSUE TITLE
postmarkOptions implemented?

### ISSUE THREAD

**Issue by ZackBoe** [killmenot/nodemailer-postmark-transport#7]
The readme mentions using `postmarkOptions` but I'm not seeing it anywhere in the library. I was hoping to be able to attach tags or metadata as per [Postmark's API](https://postmarkapp.com/developer/api/email-api) like so:
```
postmarkOptions: {
  Tag: "test-tag",
  Metadata: { "foo":"bar" }
}
```

Thanks for your time!

**Comment by killmenot** [comment]
@ZackBoe TBH I do not remember why I put it in the docs.

However, I think if pass `tags` and `metadata` props with a message and handle them in the `_parse` method https://github.com/killmenot/nodemailer-postmark-transport/blob/master/lib/postmark-transport.js#L67 you will get desired functionality. I do not think it's hard

**Comment by killmenot** [comment]
@ZackBoe 
1. Please check latest version of readme https://github.com/killmenot/nodemailer-postmark-transport#using-postmarkjs-options. I've updated it.

2. I think I will add support of tags and metadata this week-end. Then I will let you know and I need your help to test it. Will you be able to help me with it?

**Comment by killmenot** [comment]
@ZackBoe Please use latest version from master branch. You need to specify `tag` and `metadata` props in your mail object like this:
```javascript
const mail = {
   tag: 'Invitation',
   metadata: {
     color: 'blue'
  }
}
```

If it works correctly, I will release a new version soon

**Comment by ZackBoe** [comment]
@killmenot thanks so much for the quick response and work!

Both `tag` and `metadata` work as described in the `mail` object

![image](https://user-images.githubusercontent.com/904055/45231504-2a594000-b29a-11e8-8d04-3f52b76c7f7e.png)

Again, thank you for the help!

**Comment by killmenot** [comment]
@ZackBoe cool, I will release a new version tomorrow

**Comment by killmenot** [comment]
added in [1.4.0](https://github.com/killmenot/nodemailer-postmark-transport/releases/tag/1.4.0)
