### ISSUE TITLE
Getting a deprecation warning when installing

### ISSUE THREAD

**Issue by lenovouser** [killmenot/nodemailer-postmark-transport#9]
![](https://i.lenovouser.me/lvdAQ5xUldoeKqsq.jpg)

**Comment by killmenot** [comment]
@lenovouser Will take a look when find some free time. Thank you.

**Comment by killmenot** [comment]
@lenovouser Update to version 2.0.0 to get rid of it. Also please check [requirements](https://github.com/killmenot/nodemailer-postmark-transport#requirements).

**Comment by lenovouser** [comment]
@killmenot awesome!
